import "./styles/globals.css"
import { BlitzProvider } from "./blitz-client"
// import { Inter } from "next/font/google"
import Nav from "./components/Nav"
import Footer from "./components/Footer"
import { ToastProvider } from "./components/Toast"

//const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: { title: "NHMS", template: "%s – NHMS" },
  description: "Generated by Jhomari ",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <BlitzProvider>
          <Nav />
          <>{children}</>
          <ToastProvider />
        </BlitzProvider>
      </body>
    </html>
  )
}
